import Link from "next/link";  
import Image from "next/image";  


export const metadata = {
  title: "These are posts coming from WordPress.",
  description: "Generated by create next app",
};


const Posts = async () => {  
    const response = await fetch(`${process.env.NEXT_PUBLIC_WORDPRESS_API}wp-json/wp/v2/posts`);  
    const posts = await response.json();  

    // استدعاء بيانات الميديا المميزة  
    const mediaResponses = await Promise.all(  
        posts.map(async (post) => {  
            if (post.featured_media) {  
                const mediaResponse = await fetch(`${process.env.NEXT_PUBLIC_WORDPRESS_API}wp-json/wp/v2/media/${post.featured_media}`);  
                return mediaResponse.json();  
            }  
            return null; // إذا لم تكن هناك ميديا مميزة  
        })  
    );  

    return (  
        <div>  
            <h1>Posts</h1>  
            <div className="m-10 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 p-4">  
                {posts.map((post, index) => (  
                    <Link href={`/blog/${post.id}`} key={post.id}>  
                        <div className="block rounded-lg bg-white shadow-secondary-1 dark:bg-surface-dark">  
                            <div className="relative overflow-hidden bg-cover bg-no-repeat" data-twe-ripple-init data-twe-ripple-color="light">  
                                <div className="h-52 w-full overflow-hidden relative rounded-md border flex items-center justify-center">  
                                    {mediaResponses[index] ? (  
                                        <Image  
                                            src={mediaResponses[index].source_url} // استخدام URL الخاص بالصورة المميزة  
                                            width={290}  
                                            height={300}  
                                            className="rounded"  
                                            alt={mediaResponses[index].alt_text || post.title.rendered}  
                                        />  
                                    ) : (  
                                        <div className="h-full w-full flex items-center justify-center bg-gray-200">  
                                            <p>No image available</p>  
                                        </div>  
                                    )}  
                                </div>  
                                <a href="#!">  
                                    <div className="absolute bottom-0 left-0 right-0 top-0 h-full w-full overflow-hidden bg-[hsla(0,0%,98%,0.15)] bg-fixed opacity-0 transition duration-300 ease-in-out hover:opacity-100"></div>  
                                </a>  
                            </div>  
                            <div className="p-6 text-surface dark:text-white">  
                                <h5 className="mb-2 text-xl font-medium leading-tight">{post.title.rendered}</h5>  
                                <p className="mb-4 text-base">  
                                    <div  
                                        className="text-sm"  
                                        dangerouslySetInnerHTML={{  
                                            __html: post.excerpt.rendered.split(" ").slice(0, 12).join(" ").trim() + "...",  
                                        }}  
                                    ></div>  
                                </p>  
                                <button  
                                    type="button"  
                                    className="inline-block rounded bg-primary px-6 pb-2 pt-2.5 text-xs font-medium uppercase leading-normal text-white shadow-primary-3 transition duration-150 ease-in-out hover:bg-primary-accent-300 hover:shadow-primary-2 focus:bg-primary-accent-300 focus:shadow-primary-2 focus:outline-none focus:ring-0 active:bg-primary-600 active:shadow-primary-2 dark:shadow-black/30 dark:hover:shadow-dark-strong dark:focus:shadow-dark-strong dark:active:shadow-dark-strong"  
                                    data-twe-ripple-init  
                                    data-twe-ripple-color="light">  
                                    Button  
                                </button>  
                            </div>  
                        </div>  
                    </Link>  
                ))}  
            </div>  
        </div>  
    );  
};  

export default Posts;

